################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
LD_SRCS := 
TODISASSEMBLE_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_UPPER_SRCS := 
TOPREPROCESS_SRCS := 
ASM_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
EXECUTABLES := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
DAL/src/S32SDK \
NxpNfcRdLib/comps/phCidManager/src/Sw \
NxpNfcRdLib/comps/phCidManager/src \
NxpNfcRdLib/comps/phCryptoRng/src/Sw \
NxpNfcRdLib/comps/phCryptoRng/src \
NxpNfcRdLib/comps/phCryptoSym/src/Sw \
NxpNfcRdLib/comps/phCryptoSym/src \
NxpNfcRdLib/comps/phKeyStore/src/Ncx3320 \
NxpNfcRdLib/comps/phKeyStore/src/Sw \
NxpNfcRdLib/comps/phKeyStore/src \
NxpNfcRdLib/comps/phLog/src \
NxpNfcRdLib/comps/phNfcLib/src \
NxpNfcRdLib/comps/phTMIUtils/src \
NxpNfcRdLib/comps/phTools/src \
NxpNfcRdLib/comps/phacDiscLoop/src/Sw \
NxpNfcRdLib/comps/phacDiscLoop/src \
NxpNfcRdLib/comps/phalFelica/src/Sw \
NxpNfcRdLib/comps/phalFelica/src \
NxpNfcRdLib/comps/phalI18000p3m3/src/Sw \
NxpNfcRdLib/comps/phalI18000p3m3/src \
NxpNfcRdLib/comps/phalICode/src/Sw \
NxpNfcRdLib/comps/phalICode/src \
NxpNfcRdLib/comps/phalMfNtag42XDna/src/Sw \
NxpNfcRdLib/comps/phalMfNtag42XDna/src \
NxpNfcRdLib/comps/phalMfc/src/Sw \
NxpNfcRdLib/comps/phalMfc/src \
NxpNfcRdLib/comps/phalMfdf/src/Sw \
NxpNfcRdLib/comps/phalMfdf/src \
NxpNfcRdLib/comps/phalMfdfLight/src/Sw \
NxpNfcRdLib/comps/phalMfdfLight/src \
NxpNfcRdLib/comps/phalMful/src/Sw \
NxpNfcRdLib/comps/phalMful/src \
NxpNfcRdLib/comps/phalT1T/src/Sw \
NxpNfcRdLib/comps/phalT1T/src \
NxpNfcRdLib/comps/phalTop/src/Sw \
NxpNfcRdLib/comps/phalTop/src \
NxpNfcRdLib/comps/phalVca/src/Sw \
NxpNfcRdLib/comps/phalVca/src \
NxpNfcRdLib/comps/phceT4T/src/Sw \
NxpNfcRdLib/comps/phceT4T/src \
NxpNfcRdLib/comps/phhalHw/src/Ncx3320 \
NxpNfcRdLib/comps/phhalHw/src/Ncx3330 \
NxpNfcRdLib/comps/phhalHw/src/PN7462AU \
NxpNfcRdLib/comps/phhalHw/src \
NxpNfcRdLib/comps/phlnLlcp/src/Sw \
NxpNfcRdLib/comps/phlnLlcp/src \
NxpNfcRdLib/comps/phnpSnep/src/Sw \
NxpNfcRdLib/comps/phnpSnep/src \
NxpNfcRdLib/comps/phpalEpcUid/src/Sw \
NxpNfcRdLib/comps/phpalEpcUid/src \
NxpNfcRdLib/comps/phpalFelica/src/Sw \
NxpNfcRdLib/comps/phpalFelica/src \
NxpNfcRdLib/comps/phpalI14443p3a/src/Sw \
NxpNfcRdLib/comps/phpalI14443p3a/src \
NxpNfcRdLib/comps/phpalI14443p3b/src/Sw \
NxpNfcRdLib/comps/phpalI14443p3b/src \
NxpNfcRdLib/comps/phpalI14443p4/src/Sw \
NxpNfcRdLib/comps/phpalI14443p4/src \
NxpNfcRdLib/comps/phpalI14443p4a/src/Sw \
NxpNfcRdLib/comps/phpalI14443p4a/src \
NxpNfcRdLib/comps/phpalI14443p4mC/src/Sw \
NxpNfcRdLib/comps/phpalI14443p4mC/src \
NxpNfcRdLib/comps/phpalI18000p3m3/src/Sw \
NxpNfcRdLib/comps/phpalI18000p3m3/src \
NxpNfcRdLib/comps/phpalI18092mPI/src/Sw \
NxpNfcRdLib/comps/phpalI18092mPI/src \
NxpNfcRdLib/comps/phpalI18092mT/src/Sw \
NxpNfcRdLib/comps/phpalI18092mT/src \
NxpNfcRdLib/comps/phpalMifare/src/Sw \
NxpNfcRdLib/comps/phpalMifare/src \
NxpNfcRdLib/comps/phpalSli15693/src/Sw \
NxpNfcRdLib/comps/phpalSli15693/src \
Project_Settings/Startup_Code \
S32KSDK_S32K118_PE \
S32KSDK_SDK3.0.3/platform/devices/S32K118/startup \
S32KSDK_SDK3.0.3/platform/devices \
S32KSDK_SDK3.0.3/platform/drivers/src/clock/S32K1xx \
S32KSDK_SDK3.0.3/platform/drivers/src/edma \
S32KSDK_SDK3.0.3/platform/drivers/src/flexcan \
S32KSDK_SDK3.0.3/platform/drivers/src/interrupt \
S32KSDK_SDK3.0.3/platform/drivers/src/lpit \
S32KSDK_SDK3.0.3/platform/drivers/src/lpspi \
S32KSDK_SDK3.0.3/platform/drivers/src/lpuart \
S32KSDK_SDK3.0.3/platform/drivers/src/pins \
S32KSDK_SDK3.0.3/rtos/osif \
phOsal/src/NullOs \
phOsal/src/NullOs/portable \
src \

